version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: usmap_mongo
    restart: unless-stopped
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init-states.js:ro
      - mongodata:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: usmap_backend
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  # frontend:
  #   build: ./frontend
  #   container_name: usmap_frontend
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - backend

volumes:
  mongodata:
